"""Generate forwarding stubs for the proxied system DLL (dsound.dll from SysWOW64).

dsound is the proxy name because the compatibility shims Windows applies to WW.EXE
(AcGenral/AcSpecfc) preload winmm, ddraw, comctl32 and comdlg32 from System32, and the
loader then ignores same-named DLLs in the game folder.
"""
from pathlib import Path

import pefile

PROXIED = "dsound"
REAL = Path(r"C:\Windows\SysWOW64") / f"{PROXIED}.dll"
HERE = Path(__file__).resolve().parent

pe = pefile.PE(str(REAL), fast_load=True)
pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])
exports = [(e.ordinal, e.name.decode() if e.name else None) for e in pe.DIRECTORY_ENTRY_EXPORT.symbols]

defs = [f"LIBRARY {PROXIED}", "EXPORTS"]
decls, table = [], []
for i, (ordinal, name) in enumerate(exports):
    stub = f"stub_{i}"
    if name:
        defs.append(f"    {name}={stub} @{ordinal}")
        table.append(f'    {{ "{name}", 0 }},')
    else:
        defs.append(f"    ord{ordinal}={stub} @{ordinal} NONAME")
        table.append(f"    {{ nullptr, {ordinal} }},")
    decls.append(f"extern \"C\" __declspec(naked) void {stub}() {{ __asm jmp dword ptr [g_real + {i * 4}] }}")

(HERE / "src" / f"{PROXIED}.def").write_text("\n".join(defs) + "\n")
(HERE / "src" / "proxy_stubs.inc").write_text(
    f"// Generated by gen_exports.py from {REAL.name}; do not edit.\n"
    f"#define PROXIED_DLL \"{PROXIED}.dll\"\n"
    f"#define PROXY_EXPORT_COUNT {len(exports)}\n"
    "static const ExportName kExports[PROXY_EXPORT_COUNT] = {\n" + "\n".join(table) + "\n};\n"
    "extern \"C\" void* g_real[PROXY_EXPORT_COUNT];\n" + "\n".join(decls) + "\n"
)
print(f"{len(exports)} exports of {REAL.name}")
